# This is a basic workflow to help you get started with Actions

name: Autogenerate (Batch 0)

on:
  push:
    branches: [ autogenerate ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config user.name "Autogenerator Pipeline"
          git config user.email "azure-resource-manager-schemas@noreply.github.com"

      - name: Integrate main branch
        run: |
          git checkout autogenerate
          git pull
          git merge --no-commit --no-ff --strategy-option=theirs origin/master --allow-unrelated-histories
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Merge remote-tracking branch 'origin/master' into autogenerate"
            git push origin autogenerate
          fi
          
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          
      - name: Install packages
        run: npm install
        working-directory: ./generator
              
      - name: Generate Schemas
        run: |
          npm run generate-all '{"batchCount": 4, "batchIndex": 0}'
        working-directory: ./generator
        
      - name: Commit autogenerated schemas
        run: |
          git add --all schemas
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Autogenerate schemas"
            git push origin autogenerate
          fi
      
      - name: List resources
        run: |
          npm run list-resources resources.json
      
      - name: Commit resource list
        run: |
          git add generator/resources.json
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update resource list"
            git push origin autogenerate
          fi
